// <auto-generated />
using LeThiChang070.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LeThiChang070.Migrations
{
    [DbContext(typeof(LeThiChang070Context))]
    [Migration("20211016133947_Create_Table_LTC070")]
    partial class Create_Table_LTC070
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("LeThiChang070.Models.LTC070", b =>
                {
                    b.Property<string>("LTCID")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("LTCGender")
                        .HasColumnType("bit");

                    b.Property<string>("LTCName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("LTCID");

                    b.ToTable("LTC070");
                });

            modelBuilder.Entity("LeThiChang070.Models.PersonLTC070", b =>
                {
                    b.Property<string>("PersonID")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PersonName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("PersonID");

                    b.ToTable("PersonLTC070");
                });
#pragma warning restore 612, 618
        }
    }
}
